# ASP.NET Core

trigger:
- main

pool:
  name: 'Azure Pipelines'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configure $(buildConfigration)
  displayName: 'dotnet build $(buildConfiguration)'
